repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.6
  hooks:
    - id: ruff
      args: [--fix]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    exclude: ^(doc/_build|doc/styles/|doc/source/_static/highlight.css)
